.PHONY: clean All

All:
	@echo "----------Building project:[ capsSwitch - Debug ]----------"
	@cd "capsSwitch" && "$(MAKE)" -f  "capsSwitch.mk"
clean:
	@echo "----------Cleaning project:[ capsSwitch - Debug ]----------"
	@cd "capsSwitch" && "$(MAKE)" -f  "capsSwitch.mk" clean
