.PHONY: clean All

All:
	@echo "----------Building project:[ UOCLibrary - Release ]----------"
	@"$(MAKE)" -f  "UOCLibrary.mk"
clean:
	@echo "----------Cleaning project:[ UOCLibrary - Release ]----------"
	@"$(MAKE)" -f  "UOCLibrary.mk" clean
