.PHONY: clean All

All:
	@echo "----------Building project:[ Discounts - Debug ]----------"
	@cd "Discounts" && "$(MAKE)" -f  "Discounts.mk"
clean:
	@echo "----------Cleaning project:[ Discounts - Debug ]----------"
	@cd "Discounts" && "$(MAKE)" -f  "Discounts.mk" clean
