.PHONY: clean All

All:
	@echo "----------Building project:[ pec01 - Debug ]----------"
	@"$(MAKE)" -f  "pec01.mk"
clean:
	@echo "----------Cleaning project:[ pec01 - Debug ]----------"
	@"$(MAKE)" -f  "pec01.mk" clean
