.PHONY: clean All

All:
	@echo "----------Building project:[ StudentsTeachers - Debug ]----------"
	@cd "StudentsTeachers" && "$(MAKE)" -f  "StudentsTeachers.mk"
clean:
	@echo "----------Cleaning project:[ StudentsTeachers - Debug ]----------"
	@cd "StudentsTeachers" && "$(MAKE)" -f  "StudentsTeachers.mk" clean
